### ISSUE TITLE
[feature request] animations for grid layout

### ISSUE THREAD

**Issue by gmankab** [thrombe/hyprkool#1]
> afaik there is no way to control which side the workspaces slide from as a hyprland plugin, so i recommend either turning off animations for workspaces or using animation styles that do not have directionality. (eg fade)

https://github.com/hyprwm/Hyprland/issues/5491 says there is a way

**Comment by thrombe** [comment]
hyprkool doesn't use the CPP plugin API, rather it uses Hyprland's IPC interface.
afaik there is no way to control workspace animations using the IPC interface.

now there are 2 ways i see this getting solved.
1. I could look into using the CPP plugin api from rust.
2. have Hyprland expose this functionality through the IPC interface.

I'll try to explore these when I get some free time. any other suggestions are also welcome.

BTW, Have a good time using hyprkool 😁

**Comment by gmankab** [comment]
thanks

**Comment by thrombe** [comment]
:tada: animations are now supported in version 0.5 using the new plugin.

**Comment by gmankab** [comment]
thank you!
