### ISSUE TITLE
overview not working on 0.41.1

### ISSUE THREAD

**Issue by HayyanAzzam** [thrombe/hyprkool#11]
as the title says, when run manual error " hyprkool plugin must be running for this feature to work." is returned, and while on the way, if I open overview in a different activity, and move to another activity while it is open, and close it after that, when i go back to that activity overview will still be open there

**Comment by HayyanAzzam** [comment]
+ going up and down goes left and right instead

**Comment by thrombe** [comment]
> if I open overview in a different activity, and move to another activity while it is open, and close it after that, when i go back to that activity overview will still be open there

yes. that is the intended behavior.
for hyprkool, the overview is just a workspace.

**Comment by thrombe** [comment]
> when run manual error " hyprkool plugin must be running for this feature to work."

can you check why the plugin is not running?
you can also try loading the plugin manually.

**Comment by thrombe** [comment]
> * going up and down goes left and right instead

are you talking about the animations?
animations will not work if hyprkool-plugin is not running.

**Comment by thrombe** [comment]
@HayyanAzzam hyprkool's plugin won't work for Hyprland 0.41.x right now. Hyprland is going through massive internal changes right now. so basically breaking the plugin every minor update. i was kinda waiting for those internal changes to get a bit more stable before working on hyprkool again.

i suggest using hyprland v0.40 if you really want hyprkool-plugin features.

**Comment by thrombe** [comment]
i'll close this issue now. you faced this issue most likely cuz hyprkool-plugin 0.6 does not compile for Hyprland v0.41.x.

if the issue persists for hyprkool 0.7, please reopen the issue.
