### ISSUE TITLE
Can't load the plugin using flakes and stand alone home manager.

### ISSUE THREAD

**Issue by Nero-Study-Hat** [thrombe/hyprkool#12]
My setup:
- flakes, nixos, stand alone home-manager
- here is the current state of my flake repo: [nix-flake-link](https://github.com/Nero-Study-Hat/nixos-config/tree/desktop-module-expansion)

Issue:
- the plugin won't load with the below error being displayed at the top of my active monitor in read when it is attempted

`failed to load the following plugins: /nix/store/{hash-path-details}/libhyprkool.so`

What I found:
- in the nix store dir where the plugin is (copied from the hyprland.conf) 'ls -a' reveals only a `bin` dir to exist
- within this bin dir is a file named "hyprkool" which is a `LSB executable` (found with the 'file' command)

I have been trying to set up a minimal virtual machine image generator for you to test this issue with but this has proven harder than I expected so that is still in progress. I am not really able to solve this on my own as I am very new to hyprland and don't know C++ so I am not sure what is going on in the source code.

I really think the idea of this project is cool as one of the first things I looked into with hyprland was how to get the virtual desktops and activities experience of kde as those were amazing.

**Comment by thrombe** [comment]
i didn't realize the plugin building broke with another minor hyprland version 😓. i pushed a [new release](https://github.com/thrombe/hyprkool/releases/tag/0.7.1) for Hyprland v0.41.2.

other than that, you are installing the wrong package for `hyprkool-plugin` [here](https://github.com/Nero-Study-Hat/nixos-config/blob/desktop-module-expansion/users/test-hyprkool/hyprland-test.nix#L43-L46).
you have to install the `hyprkool-plugin` package as [mentioned in the readme](https://github.com/thrombe/hyprkool/blob/master/README.md?plain=1#L106-L109).

another thing, you should add something like the following in your [flake inputs](https://github.com/Nero-Study-Hat/nixos-config/blob/desktop-module-expansion/flake.nix#L39-L42) if the plugin fails to build.
```nix
hyprkool = {
  url = "github:thrombe/hyprkool/0.7.1";
  inputs.nixpkgs.follows = "nixpkgs";
  inputs.nixpkgs-unstable.follows = "nixpkgs";
  inputs.hyprland.follows = "hyprland";
};
```
i.e. use the same nixpkgs as your hyprland input and [pin hyprkool version that supports hyprland v0.41.2](https://github.com/thrombe/hyprkool/blob/e0ae6c6b6513eaa70540fea200031743e4b62165/README.md?plain=1#L36).

**Comment by Nero-Study-Hat** [comment]
Sorry for taking so long to get back to you on this and thanks for taking some time to help. I tried the fixes you suggested (held my face in hands for a moment when I saw the hyprkool-plugin one) and the shared object file exists as it should now but the plugin still did not work.

When I tried with nixpkgs-unstable (which I am using for everything almost) I got the below error.
![image](https://github.com/user-attachments/assets/887e046c-4fcc-454d-b011-f4c311783d07)
The commit with this code is here:  [commit-link](https://github.com/Nero-Study-Hat/nixos-config/tree/64e26b9773a0d38802358d74db691d4eb3f1e91e)

Using `ls -la` here is what I got on the shared object file.
`-r-xr-xr-x 3 root root 671176 Dec 31  1969 libhyprkool.so`
The commit with this code is here: [commit-link](https://github.com/Nero-Study-Hat/nixos-config/tree/c72aacdf06efc2643a060c87e8fec3c39d739408)

When I tried with nixpkgs-stable for hyprland and plugin inputs for it I got the same error and when I rebooted and went through the ssdm login I found I could not get into hyprland.

**Comment by thrombe** [comment]
> I have been trying to set up a minimal virtual machine image generator for you to test this issue with but this has proven harder than I expected so that is still in progress.

i ended up doing this as well. thanks for the idea. newer versions of Hyprland refuse to launch in the version of Hyprland i am using, so this VM is pretty helpful.

this "File could not be opened for reading" error is a bug. it will be fixed in the next hyprkool release. for now, just create a file in the location `~/.config/hypr/hyprkool.toml`. plugin crashes when it can't find hyprkool's config file.

**Comment by Nero-Study-Hat** [comment]
Happy to help and that did it for me. The plug-in works now. I also handled the issue of the file possibly not existing [here](https://github.com/Nero-Study-Hat/nixos-config/blob/desktop-module-expansion/modules/home/hyprland/plugins/hyprkool.nix) by creating a tiny shell script to check if the file exists and copy the one in my projects config directory if the file doesn't exist.

I am going to stick to using the custom activities setup I have gotten up and running by extending the virtual-desktops plugin with some personal programs for now because of my multi-monitor setup (each with abnormal aspect ratios) not really being supported by this project and my interest in the custom setup I have started. Still, I would be happy to help test this project if you could use any help.

Currently the overview highlights and mouse positioning is all bent out of shape for me based on my monitor setup I presume. I have an ultrawide and vertical monitor. Also when mouse switching is enabled and there is an empty toml file it gets the edge of my screen wrong and I lose a portion of my ultrawide monitor. Should I copy this stuff over to the active multi-monitor issue that is open?

**Comment by thrombe** [comment]
> I am going to stick to using the custom activities setup I have gotten up and running ...


sure! i'm happy you gave hyprkool a try.

> Should I copy this stuff over to the active multi-monitor issue that is open?


sure. that would help when i work on the issue. if you don't mind, can you phrase your explanation a little differently? i am having a little trouble understanding this version.

i'll leave the issue open for now. it should auto close when the commit for the fix lands in master.
