### ISSUE TITLE
Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by frigaut** [thrombe/hyprkool#3]
Hi!
First issue?
I saw your (?) post on reddit and wanted to try hyprkool out. It looks lie something I have been looking for for a while.
Anway, tried to install it through hyprpm (it worked) but trying to run it I get

〉hyprpm list           
[...]
 → Repository hyprkool:
  │ Plugin hyprkool
  └─ enabled: true
[22:02 ~/Downloads]
〉hyprkool toggle-overview
zsh: hyprkool: command not found...

I then tried to install it from source, it built, but then

〉./target/release/hyprkool toggle-overview
Error: No such file or directory (os error 2)

the executable is there, and I can 

〉./target/release/hyprkool                
A tool that helps you replicate the feel of kde activities and desktop grid layout in Hyprland

Usage: hyprkool [OPTIONS] <COMMAND>

Commands:
  daemon                           
  daemon-quit                      
  [...]

but trying to execute any command (daemon, toggle-overview) lead to the same

〉./hyprkool toggle-overview
Error: No such file or directory (os error 2)

any hint?

**Comment by thrombe** [comment]
you have to install both the plugin and the cli for the overview to work.
the cli can be installed with this command `cargo install --path .` after you cd into this repo.
after installing the cli - can you make sure that other commands are running?
you can test `hyprkool info active-window'

**Comment by thrombe** [comment]
it seems like you might not have the `hyprkool.toml` config file in place.
can you try copy pasting the contents of hyprkool.toml from the readme file to `~/.config/hypr/hyprkool.toml` ?

either way, this should have just picked up the default values. i'll fix this bug shortly.

**Comment by thrombe** [comment]
commit 454c82b should solve this issue.

**Comment by thrombe** [comment]
i'll close the issue as it should be fixed. you can reopen it if you still face this issue after updating hyprkool.
