### ISSUE TITLE
nix: filename of the shared object doesn't have `lib` prefix

### ISSUE THREAD

**Issue by postsolar** [thrombe/hyprkool#4]
The following HM option

```nix
wayland.windowManager.hyprland.plugins = [
  inputs.hyprkool.packages.${pkgs.system}.hyprkool-plugin
];
```

will generate a line like this in final `hyprland.conf`
```
plugin=/nix/store/6ym96zfmf7qy2x732qjm0cap43ns7vsc-hyprkool-0.5.0/lib/libhyprkool.so
```
but the path of the lib is actually `/nix/store/<hash>-hyprkool-0.5.0/lib/hyprkool.so`, without the `lib` prefix.

Every plugin I've seen has `lib` prefix, so I guess `hyprkool` should too.

Hyprkool pin: [564b7f8](https://github.com/thrombe/hyprkool/commit/564b7f8daeb53dae66cd93a00f5a3a788674d868)

**Comment by thrombe** [comment]
i see. i did not try the home-manager plugin because of how i have set up hyprland. i'll add the 'lib' and push a fix.

**Comment by thrombe** [comment]
added 'lib' prefix in commit 60652b7.
can you check if it works for you now?

**Comment by postsolar** [comment]
Yep now there's no need to change it manually. Thank you
