### ISSUE TITLE
No Such file or deirectory

### ISSUE THREAD

**Issue by HayyanAzzam** [thrombe/hyprkool#9]
Hey there again, hope you r doing well, I just updated to hyprland 0.40.0-1 (latest on extra), hyprkool simply stopped working, when running "hyprkool" in the terminal i get the help message, but when running `hyprkool daemon -m` i get `Error: No such file or directory (os error 2)`. 

I updated the daemon and the plugin from hyprpm, but to no avail, and using the entore path to run the thingy has the same result, when running `~/.cargo/bin/hyprkool` i get the help message, but when running `~/.cargo/bin/hyprkool daemon - m` i get `Error: No such file or directory (os error 2)` 

![image](https://github.com/thrombe/hyprkool/assets/71053124/1c608cd9-4fcc-4f9c-b540-17235f3c9f74)

**Comment by HayyanAzzam** [comment]
tested on these, only works on this one 
![image](https://github.com/thrombe/hyprkool/assets/71053124/81f9c36c-698f-4474-b2c0-61a9ea273ef8)

**Comment by HayyanAzzam** [comment]
> hyprland changed a bunch of things in v0.40 and i haven't done the work to support that yet.
> 
> i'll push fixes for it in the near future. until then, hyprkool will only work with v0.39.
> 
> apologies for the inconvenience.

ok ok, lovely, thx

**Comment by thrombe** [comment]
let's keep the issue open until it is fixed. :)
